spring:
  application:
    name: config-service
#  cloud:
#    config:
#      fail-fast: true
#      server:
#        git:
#          uri: https://github.com/debangshud/micro-services.git
#          search-paths: config-source/src/main/resources
#          username: "debangshud"
#          password: "')BsFc69"
#server:
#  port: 8888
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka/}

