---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 341f60418839e1f184f058dd473b8717a1f9177a
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: oauth-service
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.dasgupta
    name: oauth-service
  spec:
    ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: oauth-service
      provider: fabric8
      group: org.dasgupta
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 341f60418839e1f184f058dd473b8717a1f9177a
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=oauth-service&var-version=0.0.1-SNAPSHOT
    labels:
      app: oauth-service
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.dasgupta
    name: oauth-service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: oauth-service
      provider: fabric8
      group: org.dasgupta
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 341f60418839e1f184f058dd473b8717a1f9177a
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=oauth-service&var-version=0.0.1-SNAPSHOT
        labels:
          app: oauth-service
          provider: fabric8
          version: 0.0.1-SNAPSHOT
          group: org.dasgupta
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: oauth-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 9090
            name: websm
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: oauth-service:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: oauth-service
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.dasgupta
    name: oauth-service
  spec:
    port:
      targetPort: 9090
    to:
      kind: Service
      name: oauth-service
