server:
  port: 10003

spring:
  application:
    name: spring-boot-jpa
  datasource:
    url:  jdbc:oracle:thin:@//localhost:1521/xe
    username: HR
    password: HR

security:
  oauth2:
    client:
      client-id: client
      client-secret: clientpassword
      authentication-scheme: header
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
      prefer-token-info:  true

debug:  false