spring:
  application:
    name: spring-cloud-config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/debangshud/sample-spring-boot-config-repo.git
server:
  port: 8888

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#
#---
#spring:
#  profiles: container
#
#eureka:
#  client:
#    service-url:
#      default-zone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
