spring:
  application:
    name: spring-cloud-config-service
  cloud:
      config:
        server:
          git:
            uri: https://github.com/debangshud/micro-services.git
            search-paths: sample-spring-boot-config-repo
server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
