test:
  prop: custom propery

spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
    platform: postgres
    url: jdbc:postgresql://postgresql:5432/sampledb
    username: developer
    password: developer
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true