spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgresql:5432/sampledb
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        default_schema: employee_owner
        jdbc:
          lob:
            non_contextual_creation: true