spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
security:
  oauth2:
    authorization:
      check-token-access: ''
  jwt:
    key-store: classpath:certs/keystore.jks
    key-store-password: changeit
    key-pair-alias: mytestkey
    key-pair-password: changeit