spring:
  data:
    mongodb:
      database: sampledb
      authentication-database: sampledb
      host: mongodb
      port: 27017
      username: developer
      password: developer
mongock:
  change-logs-scan-package:
    - org.groodle.boot.service.reference.changelogs