eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
security:
    user:
        name: admin
        password: admin
server:
    port: 8751
spring:
    application:
        name: spring-boot-admin-server
