---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: customer-service
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: customer-service@sha256:4fa1df979c2594afe04fbb00abd58b5a2d74acb060df7c777ce0df8df319b108
        namespace: groodle
      name: latest
