---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 341f60418839e1f184f058dd473b8717a1f9177a
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: oauth-service
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: org.dasgupta
  name: oauth-service
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: oauth-service
    provider: fabric8
    group: org.dasgupta
