spring:
  application:
    name: netflix-zuul-api-gateway-server
  cloud:
    config:
      discovery:
        service-id: spring-cloud-config-service
        enabled: true
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka