spring:
  application:
    name: config-service
  cloud:
      config:
        server:
          git:
            uri: https://github.com/debangshud/micro-services.git
            search-paths: config-source
            username: "debangshud"
            password: "')BsFc69"
server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
